/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        Mikeal classUnderTest = new Mikeal();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
