/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;


import se.iths.pojo.Album;
import se.iths.pojo.Artist;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args)  {
        try {

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Chinook", "iths", "iths");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM Album LIMIT 5");

            List<Album> albums = new ArrayList<>();

            while(rs.next()){
                int id = rs.getInt(1);
                String albumName = rs.getString(2);
                albums.add(new Album(id,albumName));
            }

            for (Album i:albums){
                System.out.println(i);
            }

        } catch (SQLException e) {
            System.out.println("Något gick fel vid inläsning av databas! " + e);
        }
    }

    private void load() throws SQLException {
        List<Artist> artists = loadArtists();
        for(Artist artist: artists){
            System.out.println(artist);
        }
    }

    private List<Artist> loadArtists() throws SQLException {
        List<Artist> artists = new ArrayList<>();
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Chinook", "iths", "iths");
        ResultSet rs = con.createStatement().executeQuery("SELECT ArtistId, AlbumId, Name, Title FROM Artist JOIN Album USING (ArtistId) ORDER BY ArtistId");



        while(rs.next()){
            int id = rs.getInt("ArtistId");
            String name = rs.getString("Name");
            Artist artist = new Artist(id, name);
            artists.add(artist);
            List<Album> albums = loadAlbums(artist.getId());
            for(Album i : albums) {
                artist.add(i);
            }
        }
        rs.close();
        con.close();
        return artists;
    }
    private List<Album> loadAlbums(int artistId) throws  SQLException{
        Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/Chinook", "iths", "iths");
        List<Album> albums = new ArrayList<>();

        PreparedStatement stmt = con.prepareStatement("SELECT AlbumId,Title FROM Album WHERE ArtistId =?");
        stmt.setInt(1, artistId);//Sätt värde för första frågetecknet
        ResultSet rs = stmt.executeQuery();
        while(rs.next()){
            int id = rs.getInt(1);
            String title = rs.getString(2);
            Album album = new Album(id, title);
            albums.add(album);
        }
        stmt.close();
        rs.close();
        con.close();
        return albums;
    }
}



